# Generated by Django 5.1.3 on 2024-12-11 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('annual_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_data', to='imf_data.country')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyData',
            fields=[
                ('quarter_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric', models.CharField(max_length=500)),
                ('quarter', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_data', to='imf_data.country')),
            ],
            options={
                'verbose_name_plural': 'quarterly data',
            },
        ),
    ]
