# Generated by Django 5.1.3 on 2024-12-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imf_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlydata',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddIndex(
            model_name='annualdata',
            index=models.Index(fields=['country', 'year'], name='imf_data_an_country_315498_idx'),
        ),
        migrations.AddIndex(
            model_name='annualdata',
            index=models.Index(fields=['metric'], name='imf_data_an_metric_564db0_idx'),
        ),
        migrations.AddIndex(
            model_name='quarterlydata',
            index=models.Index(fields=['country', 'year'], name='imf_data_qu_country_7c4921_idx'),
        ),
        migrations.AddIndex(
            model_name='quarterlydata',
            index=models.Index(fields=['metric'], name='imf_data_qu_metric_c40ae4_idx'),
        ),
    ]
