-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.annual_data
(
    annual_id integer NOT NULL,
    country_id integer,
    country character varying(100) COLLATE pg_catalog."default",
    metric character varying(500) COLLATE pg_catalog."default",
    year integer,
    value numeric(15, 2),
    CONSTRAINT annual_data_pkey PRIMARY KEY (annual_id)
);

CREATE TABLE IF NOT EXISTS public.countries
(
    country_id integer NOT NULL,
    country character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT countries_pkey PRIMARY KEY (country_id),
    CONSTRAINT countries_country_key UNIQUE (country)
);

CREATE TABLE IF NOT EXISTS public.quarterly_data
(
    quarter_id integer NOT NULL,
    country_id integer,
    country character varying(100) COLLATE pg_catalog."default",
    metric character varying(500) COLLATE pg_catalog."default",
    quarter character varying(10) COLLATE pg_catalog."default",
    value numeric(15, 2),
    CONSTRAINT quarterly_data_pkey PRIMARY KEY (quarter_id)
);

ALTER TABLE IF NOT EXISTS public.annual_data
    ADD CONSTRAINT fk_country FOREIGN KEY (country_id)
    REFERENCES public.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF NOT EXISTS public.quarterly_data
    ADD CONSTRAINT fk_country_quarterly FOREIGN KEY (country_id)
    REFERENCES public.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;